### ISSUE TITLE
SHP Module master ticket (WIP)

### ISSUE THREAD

**Issue by qjimmy** [m-triassi/smart-home-simulator-team12#2]
@qjimmy for ownership

Tickets for Smart Home Security module:

- [ ] System shall allow users to set an away mode (GH-3)
- [ ] System shall send notification to users if any motion detectors are triggered while the user is away (GH-4)
- [ ] System shall turn on user-defined lights in and outside the house when motion detectors are triggered, or when doors/windows are open during away mode (GH-5)
- [ ] System shall allow users to set how much time should pass before alerting the authorities, when motion detectors are triggered during set away mode (GH-6)

**Comment by N0ot-No0t** [comment]
Fixed
