### ISSUE TITLE
System shall allow users to create a Home, edit a Home, create a Zone and like a Zone to a Home

### ISSUE THREAD

**Issue by YordanEvro** [m-triassi/smart-home-simulator-team12#20]
## Use Case Information
- Use Case Name: Allow users to create a Home, edit a Home, create a Zone and like a Zone to a Home
- Level: User level
- Brief Description: System shall allow users to create a Home, edit a Home, create a Zone and like a Zone to a Home
- Preconditions:
- Triggering Event: Submitting one of the forms on the page
- Main Flow: User opens Create Home page, user creates a home, edits a home or creates a zone
- Extension:
- Postcondition:

**Comment by m-triassi** [comment]
Closed by #19 #13 #15
