### ISSUE TITLE
SHP Module: System shall allow users to set an away mode

### ISSUE THREAD

**Issue by qjimmy** [m-triassi/smart-home-simulator-team12#3]
## Overview

Part of GH-2

## Use Case Information
- Use Case Name: Allow users to set an away mode
- Level: User level
- Brief Description: System gives the users the ability to set themselves as `away`
- Preconditions: Users must be valid
- Triggering Event: User click
- Main Flow: User is not away. User sets himself/herself to away. User's status is `away`.
- Extension: User is already `away`. 
- Postcondition: User's status shall be set to `away`. Must correctly display user's status.

**Comment by N0ot-No0t** [comment]
Fixed
