### ISSUE TITLE
SHP Module: Notify users if motion detectors are triggered while user is away.

### ISSUE THREAD

**Issue by qjimmy** [m-triassi/smart-home-simulator-team12#4]
## Overview
Part of GH-2

## Use Case Information
- Use Case Name: Notify users if motion detectors are triggered while user is away.
- Level: User-level
- Brief Description: System shall send notification to users if any motion detectors are triggered while the user is away
- Preconditions: Users must be set to away.
- Triggering Event: Motion detector trigger
- Main Flow: User is away. Motion detector is triggered. Send notification to user.
- Extension: User isn't away. Motion detector is triggered. Notification is not sent.
- Postcondition: Notification sent to away users on motion detector trigger.

**Comment by N0ot-No0t** [comment]
Fixed
