### ISSUE TITLE
SHP Module: Turn on user-defined lights in and outside the house when motion detectors are triggered, or when doors/windows are open during away mode

### ISSUE THREAD

**Issue by qjimmy** [m-triassi/smart-home-simulator-team12#5]
## Overview
Part of GH-2

## Use Case Information
- Use Case Name: Turn on user-defined lights in and outside the house when motion detectors are triggered, or when doors/windows are open during away mode
- Level: User-level
- Brief Description: System shall turn on user-defined lights in and outside the house when motion detectors are triggered, or when doors/windows are open during away mode
- Preconditions: User has defined-lights and is away.
- Triggering Event: Windows open, doors open or motion detector has been triggered.
- Main Flow: User is away and already has user-defined lights. One of the triggering events happens. User-defined lights are then turned on.
- Extension:
- Postcondition: User's lights are turned on.

**Comment by N0ot-No0t** [comment]
Fixed
