### ISSUE TITLE
The user shall login and set house location

### ISSUE THREAD

**Issue by Salander24** [m-triassi/smart-home-simulator-team12#9]
## Use Case Information
- Use Case Name: Login and set house location
- Level: User level
- Brief Description: The user shall be able to login with their pre-existing profile and set their house location
- Preconditions: The user's profile exists in the database
- Triggering Event: None
- Main Flow:
- Extension: The user's profile does not exist in the database
- Postcondition:

**Comment by m-triassi** [comment]
Closed by #16
